spring:
  application:
    name: challenge-monitoring-backend
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_monitoring?serverTimezone=UTC
    username: root
    password:
server:
  port: 8080